# Generated by Django 5.2.8 on 2025-11-08 07:57

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ticker', models.CharField(blank=True, max_length=12)),
                ('type', models.CharField(choices=[('stock', 'Stock'), ('bond', 'Bond'), ('crypto', 'Crypto'), ('fund', 'Index/Mutual Fund'), ('annuity', 'Annuity'), ('other', 'Other')], default='stock', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('amount_invested', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('current_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
