# Generated by Django 5.2.8 on 2025-11-09 19:45

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('fees', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=18)),
                ('executed_at', models.DateField()),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolio.investment')),
            ],
            options={
                'ordering': ['executed_at', 'id'],
            },
        ),
    ]
